spring:
  datasource:
    url: ${url:jdbc:mariadb://localhost:3306/team_fresh}
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
